baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Tara Hächler"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = '#f1c202'
  baseColor = "#000000"
  baseOffsetColor = "#eaeaea"
  headingColor = "#ffffff"
  textColor = "#ffffff"
  dotColor = "#f1c202"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap"
  fontFamilyHeading = "Dela Gothic One"
  fontFamilyParagraph = "Lexend"
  fontFamilyMonospace = "monospace"
  favicon = "/images/favicon.png"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'accueil'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "veille"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "projets"
    identifier = "projets"
    weight = 3
    url = "/projets/"
  [[menu.main]]
    name = "à propos"
    identifier = "à propos"
    weight = 4
    url = "/pages/About/"
  [[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 5
    url = "/pages/contact/"